// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ingest-error-auth'
  | 'ingest-error-network'
  | 'ingest-error-no-metadata'
  | 'ingest-error-timeout'
  | 'ingest-error-unknown'
  | 'ingest-no-selection'
  | 'ingest-start'
  | 'ingest-success'
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-ingest'
  | 'menupopup-label'
  | 'pref-api-endpoint'
  | 'pref-api-key'
  | 'pref-help'
  | 'pref-model-name'
  | 'pref-request-timeout'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
