// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiEndpoint": string;
      "apiKey": string;
      "modelName": string;
      "requestTimeout": number;
      "autoExtractConcepts": boolean;
    };
  }
}
